add review reject

diff --git a/helpers/redmine-tasks b/helpers/redmine-tasks
--- a/helpers/redmine-tasks
+++ b/helpers/redmine-tasks
@@ -14,6 +14,16 @@ function redmine_get_developers
     fi
 }
 
+function redmine_get_developers_id
+{
+    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-developers --id="$1" --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --status_id="$REDMINE_TASK_IN_PROGRESS" --ids_only 2> /dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "Can't fetch the task $1. This task exist ? Your server is properly configurated ?" 1>&2
+        exit 1
+    fi
+}
+
 function redmine_check_task
 {
     MESSAGE='DEFAULT'
