helper for developer

diff --git a/helpers/redmine-tasks b/helpers/redmine-tasks
--- a/helpers/redmine-tasks
+++ b/helpers/redmine-tasks
@@ -3,3 +3,14 @@ function redmine_get_all_local_tasks
 {
     git config --get-regexp ^redmine.task | cut -d "." -f 3 | sort -u
 }
+
+function redmine_get_developers
+{
+    /usr/local/share/Git-Redmine-Suite/helpers/redmine-get-developers --id="$1" --auth_key="$REDMINE_AUTHKEY" --server_url="$REDMINE_URL" --status_id="$REDMINE_TASK_IN_PROGRESS" 2> /dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "Can't fetch the task $1. This task exist ? Your server is properly configurated ?" 1>&2
+        exit 1
+    fi
+}
+
